# Generated by Django 4.1.4 on 2024-02-28 18:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('New1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('healers', 'Хилы'), ('tanks', 'Танки'), ('dd', 'ДД'), ('dealers', 'Торговцы'), ('gildmasters', 'Гилдмастеры'), ('questgivers', 'Квестгиверы'), ('blacksmiths', 'Кузнецы'), ('tanners', 'Кожевники'), ('potionsmakers', 'Зельевары'), ('spell_masters', 'Мастера заклинаний')], default='healers', max_length=25, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Вводите текст сюда...', verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Введите заголовок...', max_length=30, verbose_name='Названиe'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(default='Введите текст отклика...', verbose_name='Отклик'),
        ),
    ]
