# Generated by Django 4.1.4 on 2024-03-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New1', '0002_alter_post_author_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Здесь должен быть заголовок...', max_length=128, verbose_name='Названиe'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(default='', verbose_name='Отклик'),
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='New1.post')),
            ],
        ),
    ]
