# Generated by Django 4.1.4 on 2024-03-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New1', '0003_alter_post_title_alter_response_text_postcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='postTrough',
        ),
    ]
