# Generated by Django 4.1.4 on 2024-03-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New1', '0004_remove_postcategory_posttrough'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='Subscriptions',
        ),
    ]
