# Generated by Django 4.1.4 on 2024-03-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New1', '0008_rename_subscriptions_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
