# Generated by Django 4.1.4 on 2024-04-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='code',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='user',
        ),
    ]
